package com.ireald.wp.mapper;

import com.ireald.wp.core.mybaits.mapper.BaseMapper;
import com.ireald.wp.domain.Dept;

public interface DeptMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    int deleteByPrimaryKey(String dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    Dept selectByPrimaryKey(String dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    int updateByPrimaryKey(Dept record);
    
    Dept selectWithRoleByPrimaryKey(String dept_id);
}