package com.ireald.wp.mapper;

import com.ireald.wp.core.mybaits.mapper.BaseMapper;
import com.ireald.wp.domain.DeptAssoRole;

public interface DeptAssoRoleMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_role
     *
     * @mbggenerated Wed May 28 21:25:43 CST 2014
     */
    int deleteByPrimaryKey(String role_dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_role
     *
     * @mbggenerated Wed May 28 21:25:43 CST 2014
     */
    int insert(DeptAssoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_role
     *
     * @mbggenerated Wed May 28 21:25:43 CST 2014
     */
    int insertSelective(DeptAssoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_role
     *
     * @mbggenerated Wed May 28 21:25:43 CST 2014
     */
    DeptAssoRole selectByPrimaryKey(String role_dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_role
     *
     * @mbggenerated Wed May 28 21:25:43 CST 2014
     */
    int updateByPrimaryKeySelective(DeptAssoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_role
     *
     * @mbggenerated Wed May 28 21:25:43 CST 2014
     */
    int updateByPrimaryKey(DeptAssoRole record);
}