package com.ireald.wp.mapper;

import com.ireald.core.mybaits.mapper.BaseMapper;
import com.ireald.wp.domain.Premission;

public interface PremissionMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int deleteByPrimaryKey(String permisson_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int insert(Premission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int insertSelective(Premission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    Premission selectByPrimaryKey(String permisson_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int updateByPrimaryKeySelective(Premission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int updateByPrimaryKey(Premission record);
}