package com.ireald.wp.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.ireald.wp.core.mybaits.mapper.BaseMapper;
import com.ireald.wp.domain.User;

public interface UserMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int deleteByPrimaryKey(String user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    User selectByPrimaryKey(String user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    int updateByPrimaryKey(User record);
    
    User selectByLoginId(String loginId);
    
    User selectWithRolesByLoginId(String loginId);
    
    User selectWithDeptsByLoginId(String loginId);
    
    Long countAll();
    
    List<User> countAllbyPage(RowBounds rowBounds);
}