package com.ireald.wp.domain;

import java.util.List;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_id
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    private String dept_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.pid
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.name
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.fullname
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.code
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.serailno
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    private Integer serailno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.pinyin
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_id
     *
     * @return the value of dept.dept_id
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public String getDept_id() {
        return dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_id
     *
     * @param dept_id the value for dept.dept_id
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public void setDept_id(String dept_id) {
        this.dept_id = dept_id == null ? null : dept_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.pid
     *
     * @return the value of dept.pid
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.pid
     *
     * @param pid the value for dept.pid
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.name
     *
     * @return the value of dept.name
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.name
     *
     * @param name the value for dept.name
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.fullname
     *
     * @return the value of dept.fullname
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.fullname
     *
     * @param fullname the value for dept.fullname
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.code
     *
     * @return the value of dept.code
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.code
     *
     * @param code the value for dept.code
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.serailno
     *
     * @return the value of dept.serailno
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public Integer getSerailno() {
        return serailno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.serailno
     *
     * @param serailno the value for dept.serailno
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public void setSerailno(Integer serailno) {
        this.serailno = serailno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.pinyin
     *
     * @return the value of dept.pinyin
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.pinyin
     *
     * @param pinyin the value for dept.pinyin
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
    
    private List<Role> roles;

    public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Dept other = (Dept) that;
        return (this.getDept_id() == null ? other.getDept_id() == null : this.getDept_id().equals(other.getDept_id()))
            && (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getFullname() == null ? other.getFullname() == null : this.getFullname().equals(other.getFullname()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getSerailno() == null ? other.getSerailno() == null : this.getSerailno().equals(other.getSerailno()))
            && (this.getPinyin() == null ? other.getPinyin() == null : this.getPinyin().equals(other.getPinyin()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue May 27 21:39:52 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDept_id() == null) ? 0 : getDept_id().hashCode());
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getFullname() == null) ? 0 : getFullname().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getSerailno() == null) ? 0 : getSerailno().hashCode());
        result = prime * result + ((getPinyin() == null) ? 0 : getPinyin().hashCode());
        return result;
    }
}