package com.ireald.wp.domain;

public class PermissonAssoResoucre {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permisson_resoucre.permisson_resoucre_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String permisson_resoucre_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permisson_resoucre.permisson_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String permisson_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permisson_resoucre.resource_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String resource_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permisson_resoucre.permisson_resoucre_id
     *
     * @return the value of permisson_resoucre.permisson_resoucre_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getPermisson_resoucre_id() {
        return permisson_resoucre_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permisson_resoucre.permisson_resoucre_id
     *
     * @param permisson_resoucre_id the value for permisson_resoucre.permisson_resoucre_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setPermisson_resoucre_id(String permisson_resoucre_id) {
        this.permisson_resoucre_id = permisson_resoucre_id == null ? null : permisson_resoucre_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permisson_resoucre.permisson_id
     *
     * @return the value of permisson_resoucre.permisson_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getPermisson_id() {
        return permisson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permisson_resoucre.permisson_id
     *
     * @param permisson_id the value for permisson_resoucre.permisson_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setPermisson_id(String permisson_id) {
        this.permisson_id = permisson_id == null ? null : permisson_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permisson_resoucre.resource_id
     *
     * @return the value of permisson_resoucre.resource_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getResource_id() {
        return resource_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permisson_resoucre.resource_id
     *
     * @param resource_id the value for permisson_resoucre.resource_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setResource_id(String resource_id) {
        this.resource_id = resource_id == null ? null : resource_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisson_resoucre
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PermissonAssoResoucre other = (PermissonAssoResoucre) that;
        return (this.getPermisson_resoucre_id() == null ? other.getPermisson_resoucre_id() == null : this.getPermisson_resoucre_id().equals(other.getPermisson_resoucre_id()))
            && (this.getPermisson_id() == null ? other.getPermisson_id() == null : this.getPermisson_id().equals(other.getPermisson_id()))
            && (this.getResource_id() == null ? other.getResource_id() == null : this.getResource_id().equals(other.getResource_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permisson_resoucre
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPermisson_resoucre_id() == null) ? 0 : getPermisson_resoucre_id().hashCode());
        result = prime * result + ((getPermisson_id() == null) ? 0 : getPermisson_id().hashCode());
        result = prime * result + ((getResource_id() == null) ? 0 : getResource_id().hashCode());
        return result;
    }
}