package com.ireald.wp.domain;

import java.util.List;

public class Premission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column premission.permisson_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String permisson_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column premission.permisson
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String permisson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column premission.name
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column premission.description
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column premission.is_show
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private Boolean is_show;
    
    private List<Resource> resources;

    public List<Resource> getResources() {
		return resources;
	}

	public void setResources(List<Resource> resources) {
		this.resources = resources;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column premission.permisson_id
     *
     * @return the value of premission.permisson_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getPermisson_id() {
        return permisson_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column premission.permisson_id
     *
     * @param permisson_id the value for premission.permisson_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setPermisson_id(String permisson_id) {
        this.permisson_id = permisson_id == null ? null : permisson_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column premission.permisson
     *
     * @return the value of premission.permisson
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getPermisson() {
        return permisson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column premission.permisson
     *
     * @param permisson the value for premission.permisson
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setPermisson(String permisson) {
        this.permisson = permisson == null ? null : permisson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column premission.name
     *
     * @return the value of premission.name
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column premission.name
     *
     * @param name the value for premission.name
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column premission.description
     *
     * @return the value of premission.description
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column premission.description
     *
     * @param description the value for premission.description
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column premission.is_show
     *
     * @return the value of premission.is_show
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public Boolean getIs_show() {
        return is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column premission.is_show
     *
     * @param is_show the value for premission.is_show
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setIs_show(Boolean is_show) {
        this.is_show = is_show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Premission other = (Premission) that;
        return (this.getPermisson_id() == null ? other.getPermisson_id() == null : this.getPermisson_id().equals(other.getPermisson_id()))
            && (this.getPermisson() == null ? other.getPermisson() == null : this.getPermisson().equals(other.getPermisson()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getIs_show() == null ? other.getIs_show() == null : this.getIs_show().equals(other.getIs_show()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table premission
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPermisson_id() == null) ? 0 : getPermisson_id().hashCode());
        result = prime * result + ((getPermisson() == null) ? 0 : getPermisson().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getIs_show() == null) ? 0 : getIs_show().hashCode());
        return result;
    }
}