package com.ireald.wp.domain;

public class UserAssoDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dept.user_dept_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String user_dept_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dept.user_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dept.dept_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    private String dept_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dept.user_dept_id
     *
     * @return the value of user_dept.user_dept_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getUser_dept_id() {
        return user_dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dept.user_dept_id
     *
     * @param user_dept_id the value for user_dept.user_dept_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setUser_dept_id(String user_dept_id) {
        this.user_dept_id = user_dept_id == null ? null : user_dept_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dept.user_id
     *
     * @return the value of user_dept.user_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dept.user_id
     *
     * @param user_id the value for user_dept.user_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dept.dept_id
     *
     * @return the value of user_dept.dept_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public String getDept_id() {
        return dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dept.dept_id
     *
     * @param dept_id the value for user_dept.dept_id
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    public void setDept_id(String dept_id) {
        this.dept_id = dept_id == null ? null : dept_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserAssoDept other = (UserAssoDept) that;
        return (this.getUser_dept_id() == null ? other.getUser_dept_id() == null : this.getUser_dept_id().equals(other.getUser_dept_id()))
            && (this.getUser_id() == null ? other.getUser_id() == null : this.getUser_id().equals(other.getUser_id()))
            && (this.getDept_id() == null ? other.getDept_id() == null : this.getDept_id().equals(other.getDept_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated Sat May 17 15:14:35 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUser_dept_id() == null) ? 0 : getUser_dept_id().hashCode());
        result = prime * result + ((getUser_id() == null) ? 0 : getUser_id().hashCode());
        result = prime * result + ((getDept_id() == null) ? 0 : getDept_id().hashCode());
        return result;
    }
}